### PR TITLE
Correction of BUG in subroutine parser

### PR DESCRIPTION
**Pull request by lefessan**
Support for multiple terminals

### CODE REVIEW

**Comment by GitMensch** [comment]
This PR is a bit falsely named - but please merge that in soon, as those changes are very reasonable.
Please also do a PR "cherry-pick" of your changes upstream that are related to the extension in general, not specific to superbol.

**Comment by GitMensch** [comment]
Ping on merging this (and either enable the "issues" in this repo or explicit document in the repo that they should be created at the superbol main repe [possibly with adding a tag there]).

**Comment by GitMensch** [comment]
@nberth Is there any chance you can have a look at merging this?

**Comment by nberth** [comment]
Closing in favor of the more manageable #3.

**Pull request closed without merging**
